#! /usr/bin/env bash

# Command which watches the load times of a number of websties.
#
# by torstein
#
# Example usage:
#
# watch-websites www.spiegel.de edition.cnn.com example.com

source $(dirname $0)/../common/text/color.sh

## $1 :: start
## $@ :: end
function get_load_time() {
  local time=$(( end - start ))

  if [ $time -gt 5 ]; then
    echo $(red ${time}"s")
  else
    echo $(green ${time}"s")
  fi
}

function check_site() {
  local start=$(date +%s)
  local full="$(
    curl -v http://$1 2>&1
  )"
  local end=$(date +%s)

  echo $(date +%H:%M:%S) $1 \
    $(get_load_time $start $end) \
    $(echo "$full" | sed -n 's#[<][ ]HTTP/.* \([0-9]*\) .*#\1#p') \
    $(echo "$full" | wc -c)
}

function check_all_sites() {
  for el in $@; do
    check_site $el
  done
}

while true; do
  check_all_sites $@ | column -t
done
