#! /usr/bin/env bash

# Command which does sensible diffing of two JAR files.

# by torstein

function bootstrap_thyself() {
  local required_command_list="unzip"
  for el in $required_command_list; do
    which $el &>/dev/null || {
      echo "You must have $el installed"
      exit 1
    }
  done
}

function main() {
  diff -w \
    <(cd $(dirname ${from_jar}) && unzip -t $(basename ${from_jar})) \
    <(cd $(dirname ${to_jar}) && unzip -t $(basename ${to_jar}))
}

function print_usage() {
  cat <<EOF
Usage: $(basename $0) OPTIONS <one-jar> <another-jar>

OPTOINS
--help     Prints this help screen.
EOF
}

function read_user_input() {
  for el in "$@"; do
    if [[ $el == "--help" ]]; then
      print_usage
      exit 0
    fi
  done

  if [ $# -ne 2 ]; then
    print_usage
    exit 1
  fi

  # TODO proper
  from_jar=$1
  to_jar=$2
}

bootstrap_thyself
read_user_input $@
main
