#! /usr/bin/env bash

## Command which searches all JAR files for a given class.
## by torstein.k.johansen at gmail.com

_list_contents() {
  local file=$1

  if command -v unzip &> /dev/null ; then
    unzip -v "${file}" |
      awk '{print "\t"$8}'
  elif command -v jar &> /dev/null ; then
    jar tf "${file}"
  fi
}


main() {
  if [ $# -ne 2 ]; then
    echo "Usage: $(basename "$0") <dir> <class>"
    exit 1
  elif [ $# -eq 2 ]; then
    repo_dir=$1
    query=$2
  fi

  grep --recursive "${query}" "${repo_dir}" |
    awk '{print $3}' |
    sort -u |
    while read -r f; do
      printf "%s contains:\\n" "${f}"
      _list_contents "${f}" |
        grep "${query}" |
        while read -r hit; do
          printf "%s\\n" "${hit}" |
            grep --color "${query}"
        done
    done
}

main "$@"
