#! /usr/bin/env bash

## fj - find jar, trying to be smart
##
## by torstein at skybert dot net

_verbose=1
_query=

## $1 :: dir
_find_jars_in_dir() {
  local dir=$1

  if [ ${_fast-0} -eq 1 ]; then
    local domain=${_query%%/*}
    if [ -d "${dir}/${domain}" ]; then
      local company=${_query#${domain}/}
      company=${company%%/*}

      if [ -d "${dir}/${domain}/${company}" ]; then
        dir=${dir}/${domain}/${company}
      else
        dir=${dir}/${domain}
      fi
    fi
  fi

  printf "Searching for JARs in %s\n" "${dir}"

  if [ -d "${dir}" ]; then
    local result=
    result=$(
      grep --files-with-matches \
           --ignore-case \
           --recursive \
           --include "*.jar" \
           --fixed-strings \
           "${_query}" \
           "${dir}" |
        egrep -v '(sources|javadoc).jar')

    if [[ -n "${result}" && "${_verbose-0}" -eq 1 ]]; then
      printf "%s\n" "${result}" |
        while read -r f; do
          printf "%s \n" "${f}"
          unzip -v "${f}" |
            grep --fixed-strings --ignore-case "${_query}" |
            awk '{print "   → " $8;}' |
            grep --fixed-strings --ignore-case --color "${_query}"
        done
    fi
  fi
}


_find_jars_in_maven_repo() {
  local dir="${HOME}/.m2/repository"
  _find_jars_in_dir "${dir}"
}

_find_jars_in_tomcat() {
  _find_jars_in_dir /opt/tomcat-engine1
}

_find_jars_in_cwd() {
  :
}

_ensure_sanity() {
  :
}

_make_sense_of_query() {
  :
}

main() {
  _query=$1
  _ensure_sanity
  _make_sense_of_query
  _find_jars_in_maven_repo
  printf "\n"
  _find_jars_in_tomcat
  printf "\n"
  _find_jars_in_cwd
}

main "$*"
