#! /usr/bin/env bash

header_file=$(dirname $0)/header.html
footer_file=$(dirname $0)/footer.html

output_file=$(mktemp)
src_dir=$HOME/src/skybert-net/src

source ../common-lib/indispensable.sh || {
  echo "indispensible.sh is indispensible for $(basename $0)"
  exit 1
}

function create_target_dir() {
  local dir_fragment=$(echo $1 | sed "s#${src_dir}/##")
  target_dir=$(dirname $src_dir)/generated/${dir_fragment}
  make_dir $target_dir
}

function fix_title() {
  title=$(sed -n 's/^#+TITLE: \(.*\)/\1/p' $1)
  run sed -i "s~<title>\(.*\)</title>~<title>${title}</title>~" $output_file
}

function get_file_name() {
  echo "$title" | tr '[A-Z]' '[a-z]' | \
    sed 's/[,!?_ ]/-/g'
}

function convert_org_to_html() {
  cat $header_file > $output_file
  sed -f $(dirname $0)/$(basename $0).sed $1 >> $output_file
  cat $footer_file >> $output_file
}

function convert_file() {
  convert_org_to_html $1
  create_target_dir $1
  fix_title $1

  final_fn=${target_dir}/$(get_file_name).html
  cat $output_file | xmllint --format - > $final_fn
  run rm $output_file
  print $final_fn "is now ready"
}

find $src_dir -name "*.org" | while read f; do
  convert_file "$f"
done
